### ISSUE TITLE
Failing silently on Album Download

### ISSUE THREAD

**Issue by milhouse-is-a-meme** [codeandcats/sg-scraper#9]
```
$ sg-scraper scrape https://www.suicidegirls.com/girls/radeo/album/1328978/lolly/
Getting Home Page...
Success (200)
Logging in...
Success (201)
Getting Album Page...
```

Then nothing.

**Comment by codeandcats** [comment]
Yeah sorry about that, someone messaged me about this recently and I looked into it.

Aside from the error handling needing improvement, it seems that sg have added protection against bots in the form of Google reCAPTCHA.

From some initial investigation it looks possible to get around this by, but unfortunately I just don't have the time to dedicate to it. Though I do accept PRs if you feel up to the challenge!

I will update the read me to let people know the project no longer works.

**Comment by milhouse-is-a-meme** [comment]
Thanks @codeandcats, I'll see what I can do on my end and if I have luck I'll push a PR.
